server:
  port: 8089
spring:
  datasource:
    driver-class-name: 
    username: root
    password: root
    url: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # Redis
  data:
    redis:
      host: 
      password: 
      port: 
      database: 0
  kafka:
    bootstrap-servers: 
    consumer:
      group-id: message-processor-group
      auto-offset-reset: earliest
    producer:
      acks: 1
      retries: 3

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lut.messageprocessor.entity
  configuration:
    map-underscore-to-camel-case: true
