server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/im-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # Redis
  data:
    redis:
      host: edgesky.cn
      password: iampig
      port: 6379
      database: 0
  kafka:
    bootstrap-servers: 172.31.208.1:9092
    consumer:
      group-id: message-processor-group
      auto-offset-reset: earliest
    producer:
      acks: 1
      retries: 3

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lut.messageprocessor.entity
  configuration:
    map-underscore-to-camel-case: true